spring:
  main:
    allow-circular-references: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 9001

api:
  boot:
    security:
      users:
        - username: bruce
          password: 123456


